title: "Tom Workbook"
author: "Tom Tang"
# logo: logo.png  # Optional
# Repository URL (for GitHub Pages)
repository:
  url: "https://github.com/tomctang/oeis"
  path_to_docs: "https://github.com/tomctang/oeis"
  branch: "gh-pages"  # Deployment branch for GitHub Pages

html:
  use_issues_button: false
  use_repository_button: true
  extra_css: ["_static/custom.css"]

# Sitemap (optional)
sitemap:
  filename: "sitemap.xml"
  base_url: "https://tomctang.github.io/oeis/"
execute:
  execute_notebooks: "off"  # Change to "auto" to execute notebooks during build

sphinx:
  config:
    html_js_files:
      - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
      - mermaid-init.js